mode: 'train' # 'train' or 'validate' or 'test'

tag: 'halfwidth:50'
verbose: true
seed: 1234

dataset:
  train:
    tfrecords: 'data/uncompressed/tf_example/training'
    idxs: 'data/tf_exmple_idxs/training/bs16'
    batchsize: 16
  valid:
    tfrecords: 'data/uncompressed/tf_example/validation'
    idxs: 'data/tf_exmple_idxs/validation/bs16'
    batchsize: 16
  test:
    tfrecords: 'data/uncompressed/tf_example/validation'
    idxs: 'data/tf_exmple_idxs/validation/bs1'
    batchsize: 1
    ckpt_path: '/home/user/daehee/SceneTransformer-pytorch/outputs/2021-09-23/18-49-50_gpu45_local_veh_nogradclip/lightning_logs/version_0/checkpoints/epoch=11-step=359213.ckpt'

# dataset:
#   train:
#     tfrecords: 'data/single_sample/data'
#     idxs: 'data/single_sample/idxs'
#     batchsize: 8
#   valid:
#     tfrecords: 'data/tfrecords'
#     idxs: 'data/idxs'
#     batchsize: 8

model:
  in_feat_dim: 9
  feature_dim: 256
  time_steps: 10
  current_step: 3
  in_dynamic_rg_dim: 3
  in_static_rg_dim: 6
  head_num: 4
  k: 4
  F: 6

device_ids: '0,1'
device_num: 2
max_epochs: 100

# hydra:
#   run:
#     dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}

