tag: ''
verbose: true
seed: 1235

# dataset:
#   train:
#     tfrecords: 'data/tf_example/training'
#     idxs: 'data/idxs_training_bs_2'
#   valid:
#     tfrecords: 'data/tf_example/validation'
#     idxs: 'data/idxs_validation_bs_2'
#   batchsize: 2

dataset:
  train:
    tfrecords: 'data/tfrecords'
    idxs: 'data/idxs'
  valid:
    tfrecords: 'data/tfrecords'
    idxs: 'data/idxs'
  batchsize: 2

model:
  in_feature_dim: 9
  feature_dim: 256
  time_steps: 10
  in_dynamic_rg_dim: 3
  in_static_rg_dim: 6
  head_num: 4
  k: 4
  F: 6

device_ids: '6,7'
device_num: 1
max_epochs: 100

hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}_local_full

