mode: 'train' # 'train' or 'validate' or 'test'
resume: false # '/home/user/daehee/SceneTransformer-pytorch/outputs/2021-12-30/13-27-54/lightning_logs/version_0/checkpoints/last.ckpt' 

tag: 'wta'
verbose: true
seed: 1234

dataset:
  train:
    tfrecords: 'data/uncompressed/tf_example/training'
    idxs: 'data/tf_exmple_idxs/training/bs4'
    batchsize: 4
    limit_train_batches: 1.0
    limit_val_batches: 0.5
    val_check_interval: 0.1
    log_every_n_steps: 100
  valid:
    tfrecords: 'data/uncompressed/tf_example/validation'
    idxs: 'data/tf_exmple_idxs/validation/bs4'
    batchsize: 4
  test:
    tfrecords: 'data/uncompressed/tf_example/validation'
    idxs: 'data/tf_exmple_idxs/validation/bs1'
    batchsize: 1
    ckpt_path: '/home/user/daehee/SceneTransformer-pytorch/outputs/2021-12-16/10-44-43/lightning_logs/version_0/checkpoints/epoch=9-step=283107.ckpt'
  halfwidth: 50
  only_veh: true
  hidden: 'BP'

viz:
  width: 500
  
# dataset:
#   train:
#     tfrecords: 'data/single_sample/data'
#     idxs: 'data/single_sample/idxs'
#     batchsize: 8
#   valid:
#     tfrecords: 'data/single_sample/data'
#     idxs: 'data/single_sample/idxs'
#     batchsize: 8
#   test:
#     tfrecords: 'data/single_sample/data'
#     idxs: 'data/single_sample/idxs'
#     batchsize: 8

model:
  in_feat_dim: 9
  feature_dim: 256
  time_steps: 10
  current_step: 3
  in_dynamic_rg_dim: 3
  in_static_rg_dim: 6
  head_num: 8
  k: 4
  F: 4

gpu_ids: [0,1]
max_epochs: 100

# hydra:
#   run:
#     dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}

