tag: ''
verbose: true
seed: 1234

dataset:
  train:
    tfrecords: 'data/tf_example/training'
    idxs: 'data/idxs_training_bs_8'
    batchsize: 8
  valid:
    tfrecords: 'data/tf_example/validation'
    idxs: 'data/idxs_validation_bs_8'
    batchsize: 8

# dataset:
#   train:
#     tfrecords: 'data/tfrecords'
#     idxs: 'data/idxs'
#     batchsize: 8
#   valid:
#     tfrecords: 'data/tfrecords'
#     idxs: 'data/idxs'
#     batchsize: 8

model:
  in_feat_dim: 9
  feature_dim: 256
  time_steps: 10
  current_step: 3
  in_dynamic_rg_dim: 3
  in_static_rg_dim: 6
  head_num: 4
  k: 4
  F: 6

device_ids: '6,7'
device_num: 2
max_epochs: 100

hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}_gpu67_local_veh_workerfixed

